---
apiVersion: v1
kind: Namespace
metadata:
  name: blog

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog
  namespace: blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - env:
        image: ashwnacharya.azurecr.io/blog:d2d6c76
        imagePullPolicy: Always
        name: blog
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: blog

