---
apiVersion: v1
kind: Namespace
metadata:
  name: blog

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog
  namespace: blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - env:
        image: ashwnacharyaacr.azurecr.io/blog:afcda12
        imagePullPolicy: Always
        name: blog
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: blog

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: blog
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - www.ashwnacharya.info
    secretName: aks-ingress-tls
  rules:
  - host: www.ashwnacharya.info
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: blog
          servicePort: 80

---
apiVersion: v1
kind: Namespace
metadata:
  name: blog-naked

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog-ingress-naked
  namespace: blog-naked
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: "https://www.ashwnacharya.info"
spec:
  tls:
  - hosts:
    - ashwnacharya.info
    secretName: aks-ingress-tls
  rules:
  - host: ashwnacharya.info


